package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Barco generated by hbm2java
 */
@Entity
@Table(name = "barco")
public class Barco  implements java.io.Serializable {

	@Id
     private String folio;
 //    private Tipoloxiabarco tipoloxiabarco;
 //    private Usuario usuario;
     private String nome;
     private Long eslora;
     private String porto;
   //  private Set usuarios = new HashSet(0);
   //  private Set artes = new HashSet(0);
   //  private Set faenas = new HashSet(0);

    public Barco() {
    }

	
    public Barco(String folio, String nome) {
        this.folio = folio;
        this.nome = nome;
    }
  
    public Barco(String folio, Tipoloxiabarco tipoloxiabarco, Usuario usuario, String nome, Long eslora, String porto, Set usuarios, Set artes, Set faenas) {
       this.folio = folio;
      // this.tipoloxiabarco = tipoloxiabarco;
  //     this.usuario = usuario;
       this.nome = nome;
       this.eslora = eslora;
       this.porto = porto;
//       this.usuarios = usuarios;
//       this.artes = artes;
//       this.faenas = faenas;
    }
   
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
//    public Tipoloxiabarco getTipoloxiabarco() {
//        return this.tipoloxiabarco;
//    }
//    
//    public void setTipoloxiabarco(Tipoloxiabarco tipoloxiabarco) {
//        this.tipoloxiabarco = tipoloxiabarco;
//    }
//    public Usuario getUsuario() {
//        return this.usuario;
//    }
//    
//    public void setUsuario(Usuario usuario) {
//        this.usuario = usuario;
//    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Long getEslora() {
        return this.eslora;
    }
    
    public void setEslora(Long eslora) {
        this.eslora = eslora;
    }
    public String getPorto() {
        return this.porto;
    }
    
    public void setPorto(String porto) {
        this.porto = porto;
    }

//    
//    public void setUsuarios(Set usuarios) {
//        this.usuarios = usuarios;
//    }
//    public Set getArtes() {
//        return this.artes;
//    }
//    
//    public void setArtes(Set artes) {
//        this.artes = artes;
//    }
//    public Set getFaenas() {
//        return this.faenas;
//    }
//    
//    public void setFaenas(Set faenas) {
//        this.faenas = faenas;
//    }




}


