package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Especie generated by hbm2java
 */
public class Especie  implements java.io.Serializable {


     private long id;
     private String nomeCientifico;
     private String path;
     private Set nomepopulars = new HashSet(0);

    public Especie() {
    }

	
    public Especie(long id) {
        this.id = id;
    }
    public Especie(long id, String nomeCientifico, String path, Set nomepopulars) {
       this.id = id;
       this.nomeCientifico = nomeCientifico;
       this.path = path;
       this.nomepopulars = nomepopulars;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNomeCientifico() {
        return this.nomeCientifico;
    }
    
    public void setNomeCientifico(String nomeCientifico) {
        this.nomeCientifico = nomeCientifico;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set getNomepopulars() {
        return this.nomepopulars;
    }
    
    public void setNomepopulars(Set nomepopulars) {
        this.nomepopulars = nomepopulars;
    }




}


