package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faena generated by hbm2java
 */
public class Faena  implements java.io.Serializable {


     private long id;
     private Arte arte;
     private Barco barco;
     private Date dataInicio;
     private Date horaInicio;
     private Date dataFin;
     private Date horaFin;
     private Float tempAire;
     private String estadoMar;
     private Float tempSuperficie;
     private Float direccionVento;
     private Float velocidadeVento;
     private Float tempFondo;
     private Integer lua;
     private Set lances = new HashSet(0);

    public Faena() {
    }

	
    public Faena(long id, Arte arte, Barco barco) {
        this.id = id;
        this.arte = arte;
        this.barco = barco;
    }
    public Faena(long id, Arte arte, Barco barco, Date dataInicio, Date horaInicio, Date dataFin, Date horaFin, Float tempAire, String estadoMar, Float tempSuperficie, Float direccionVento, Float velocidadeVento, Float tempFondo, Integer lua, Set lances) {
       this.id = id;
       this.arte = arte;
       this.barco = barco;
       this.dataInicio = dataInicio;
       this.horaInicio = horaInicio;
       this.dataFin = dataFin;
       this.horaFin = horaFin;
       this.tempAire = tempAire;
       this.estadoMar = estadoMar;
       this.tempSuperficie = tempSuperficie;
       this.direccionVento = direccionVento;
       this.velocidadeVento = velocidadeVento;
       this.tempFondo = tempFondo;
       this.lua = lua;
       this.lances = lances;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Arte getArte() {
        return this.arte;
    }
    
    public void setArte(Arte arte) {
        this.arte = arte;
    }
    public Barco getBarco() {
        return this.barco;
    }
    
    public void setBarco(Barco barco) {
        this.barco = barco;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getDataFin() {
        return this.dataFin;
    }
    
    public void setDataFin(Date dataFin) {
        this.dataFin = dataFin;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Float getTempAire() {
        return this.tempAire;
    }
    
    public void setTempAire(Float tempAire) {
        this.tempAire = tempAire;
    }
    public String getEstadoMar() {
        return this.estadoMar;
    }
    
    public void setEstadoMar(String estadoMar) {
        this.estadoMar = estadoMar;
    }
    public Float getTempSuperficie() {
        return this.tempSuperficie;
    }
    
    public void setTempSuperficie(Float tempSuperficie) {
        this.tempSuperficie = tempSuperficie;
    }
    public Float getDireccionVento() {
        return this.direccionVento;
    }
    
    public void setDireccionVento(Float direccionVento) {
        this.direccionVento = direccionVento;
    }
    public Float getVelocidadeVento() {
        return this.velocidadeVento;
    }
    
    public void setVelocidadeVento(Float velocidadeVento) {
        this.velocidadeVento = velocidadeVento;
    }
    public Float getTempFondo() {
        return this.tempFondo;
    }
    
    public void setTempFondo(Float tempFondo) {
        this.tempFondo = tempFondo;
    }
    public Integer getLua() {
        return this.lua;
    }
    
    public void setLua(Integer lua) {
        this.lua = lua;
    }
    public Set getLances() {
        return this.lances;
    }
    
    public void setLances(Set lances) {
        this.lances = lances;
    }




}


