package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Faena generated by hbm2java
 */
@Entity
@Table(name = "faena")
public class Faena  implements java.io.Serializable {

	 @Id
	 @GeneratedValue(generator = "increment")
	 @GenericGenerator(name = "increment", strategy = "increment")
     private long id;


	 
	 @JoinColumn(name = "idarte",insertable=false, updatable=false)
     @ManyToOne(optional = false, fetch = FetchType.LAZY)
     private Arte arte;
	 private Long idarte;
	 
     private long idbarco;
     private Date data_inicio;
     private Date hora_inicio;
     private Date data_fin;
     private Date hora_fin;
     private Float temp_aire;
     private Integer estado_mar;
     private Float temp_superficie;
     private Integer direccion_vento;
     private Float velocidade_vento;
     private Float temp_fondo;
     private Integer lua;
     private Integer estado_ceo;

    public Faena() {
    }

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getIdarte() {
		return idarte;
	}

	public void setIdarte(Long idarte) {
		this.idarte = idarte;
	}

	public long getIdbarco() {
		return idbarco;
	}
	

	public void setIdbarco(long idbarco) {
		this.idbarco = idbarco;
	}

	public Date getData_inicio() {
		return data_inicio;
	}

	public void setData_inicio(Date data_inicio) {
		this.data_inicio = data_inicio;
	}
	
	public Arte getArte() {
		return arte;
	}

	public void setArte(Arte arte) {
		this.arte = arte;
	}

	public Date getHora_inicio() {
		return hora_inicio;
	}

	public void setHora_inicio(Date hora_inicio) {
		this.hora_inicio = hora_inicio;
	}

	public Date getData_fin() {
		return data_fin;
	}

	public void setData_fin(Date data_fin) {
		this.data_fin = data_fin;
	}

	public Date getHora_fin() {
		return hora_fin;
	}

	public void setHora_fin(Date hora_fin) {
		this.hora_fin = hora_fin;
	}

	public Float getTemp_aire() {
		return temp_aire;
	}

	public void setTemp_aire(Float temp_aire) {
		this.temp_aire = temp_aire;
	}

	public Integer getEstado_mar() {
		return estado_mar;
	}

	public void setEstado_mar(Integer estado_mar) {
		this.estado_mar = estado_mar;
	}

	public Float getTemp_superficie() {
		return temp_superficie;
	}

	public void setTemp_superficie(Float temp_superficie) {
		this.temp_superficie = temp_superficie;
	}

	public Integer getDireccion_vento() {
		return direccion_vento;
	}

	public void setDireccion_vento(Integer direccion_vento) {
		this.direccion_vento = direccion_vento;
	}

	public Float getVelocidade_vento() {
		return velocidade_vento;
	}

	public void setVelocidade_vento(Float velocidade_vento) {
		this.velocidade_vento = velocidade_vento;
	}

	public Float getTemp_fondo() {
		return temp_fondo;
	}

	public void setTemp_fondo(Float temp_fondo) {
		this.temp_fondo = temp_fondo;
	}

	public Integer getLua() {
		return lua;
	}

	public void setLua(Integer lua) {
		this.lua = lua;
	}

	public Integer getEstado_ceo() {
		return estado_ceo;
	}

	public void setEstado_ceo(Integer estado_ceo) {
		this.estado_ceo = estado_ceo;
	}

	
    





}


