package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import com.vividsolutions.jts.geom.Point;

/**
 * Lance generated by hbm2java
 */
@Entity
@Table(name = "lance")
public class Lance  implements java.io.Serializable {

	 @Id
	 @GeneratedValue(generator = "increment")
	 @GenericGenerator(name = "increment", strategy = "increment")
     private long id;
     private Long idespecie;
     private Long idfaena;
     private Float peso;
     private Integer unidades;
     private Float peso_descarte;
     private Integer ud_descarte;
     
     @Type(type = "org.hibernate.spatial.GeometryType")
 	 private Point punto_inicio;
     
     @Type(type = "org.hibernate.spatial.GeometryType")
  	 private Point punto_fin;
     
     @JoinColumn(name = "idfaena",insertable=false, updatable=false)
     @ManyToOne(optional = false, fetch = FetchType.LAZY)
     private Faena faena;

     
     //getters and setters
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getIdespecie() {
		return idespecie;
	}

	public void setIdespecie(Long idespecie) {
		this.idespecie = idespecie;
	}

	public Long getIdfaena() {
		return idfaena;
	}

	public void setIdfaena(Long idfaena) {
		this.idfaena = idfaena;
	}

	public Float getPeso() {
		return peso;
	}

	public void setPeso(Float peso) {
		this.peso = peso;
	}

	public Integer getUnidades() {
		return unidades;
	}

	public void setUnidades(Integer unidades) {
		this.unidades = unidades;
	}

	public Float getPeso_descarte() {
		return peso_descarte;
	}

	public void setPeso_descarte(Float peso_descarte) {
		this.peso_descarte = peso_descarte;
	}

	public Integer getUd_descarte() {
		return ud_descarte;
	}

	public void setUd_descarte(Integer ud_descarte) {
		this.ud_descarte = ud_descarte;
	}

	public Point getPunto_inicio() {
		return punto_inicio;
	}

	public void setPunto_inicio(Point punto_inicio) {
		this.punto_inicio = punto_inicio;
	}

	public Point getPunto_fin() {
		return punto_fin;
	}

	public void setPunto_fin(Point punto_fin) {
		this.punto_fin = punto_fin;
	}

	public Faena getFaena() {
		return faena;
	}

	public void setFaena(Faena faena) {
		this.faena = faena;
	}



}


