package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Lance generated by hbm2java
 */
public class Lance  implements java.io.Serializable {


     private long id;
     private Faena faena;
     private Serializable xeometriaInicio;
     private Serializable xeometriaFin;
     private Set pescas = new HashSet(0);
     private Set pescas_1 = new HashSet(0);

    public Lance() {
    }

	
    public Lance(long id, Faena faena, Serializable xeometriaInicio) {
        this.id = id;
        this.faena = faena;
        this.xeometriaInicio = xeometriaInicio;
    }
    public Lance(long id, Faena faena, Serializable xeometriaInicio, Serializable xeometriaFin, Set pescas, Set pescas_1) {
       this.id = id;
       this.faena = faena;
       this.xeometriaInicio = xeometriaInicio;
       this.xeometriaFin = xeometriaFin;
       this.pescas = pescas;
       this.pescas_1 = pescas_1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Faena getFaena() {
        return this.faena;
    }
    
    public void setFaena(Faena faena) {
        this.faena = faena;
    }
    public Serializable getXeometriaInicio() {
        return this.xeometriaInicio;
    }
    
    public void setXeometriaInicio(Serializable xeometriaInicio) {
        this.xeometriaInicio = xeometriaInicio;
    }
    public Serializable getXeometriaFin() {
        return this.xeometriaFin;
    }
    
    public void setXeometriaFin(Serializable xeometriaFin) {
        this.xeometriaFin = xeometriaFin;
    }
    public Set getPescas() {
        return this.pescas;
    }
    
    public void setPescas(Set pescas) {
        this.pescas = pescas;
    }
    public Set getPescas_1() {
        return this.pescas_1;
    }
    
    public void setPescas_1(Set pescas_1) {
        this.pescas_1 = pescas_1;
    }




}


