package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA



/**
 * NomepopularId generated by hbm2java
 */
public class NomepopularId  implements java.io.Serializable {


     private long id;
     private long idespecie;

    public NomepopularId() {
    }

    public NomepopularId(long id, long idespecie) {
       this.id = id;
       this.idespecie = idespecie;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getIdespecie() {
        return this.idespecie;
    }
    
    public void setIdespecie(long idespecie) {
        this.idespecie = idespecie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NomepopularId) ) return false;
		 NomepopularId castOther = ( NomepopularId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdespecie()==castOther.getIdespecie());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getId();
         result = 37 * result + (int) this.getIdespecie();
         return result;
   }   


}


