package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA



/**
 * Nomepopular generated by hbm2java
 */
public class Nomepopular  implements java.io.Serializable {


     private NomepopularId id;
     private Especie especie;
     private String nome;

    public Nomepopular() {
    }

    public Nomepopular(NomepopularId id, Especie especie, String nome) {
       this.id = id;
       this.especie = especie;
       this.nome = nome;
    }
   
    public NomepopularId getId() {
        return this.id;
    }
    
    public void setId(NomepopularId id) {
        this.id = id;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


