package com.xeopesca.webapp.model.vos;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


/**
 * Nomepopular generated by hbm2java
 */
@Entity
@Table(name = "nomepopular")
public class Nomepopular  implements java.io.Serializable {

	// @ EmbeddedId
    // private NomepopularId id;
	 @Id
	 @GeneratedValue(generator = "increment")
	 @GenericGenerator(name = "increment", strategy = "increment")
	 private Long id;
	 
	
	 @JoinColumn(name = "idespecie",insertable=false, updatable=false)
     @ManyToOne(optional = false, fetch = FetchType.LAZY)
     private Especie especie;
     private String nome;
     private Long idespecie;

    

	public Nomepopular() {
    }

    public Nomepopular(Long id, Long idEspecie, String nome) {
       this.id = id;
       this.idespecie = idespecie;
       this.nome = nome;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Long getIdespecie() {
		return idespecie;
	}

	public void setIdespecie(Long idespecie) {
		this.idespecie = idespecie;
	}


}


