package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA



/**
 * PescaId generated by hbm2java
 */
public class PescaId  implements java.io.Serializable {


     private long idlance;
     private long idespecie;

    public PescaId() {
    }

    public PescaId(long idlance, long idespecie) {
       this.idlance = idlance;
       this.idespecie = idespecie;
    }
   
    public long getIdlance() {
        return this.idlance;
    }
    
    public void setIdlance(long idlance) {
        this.idlance = idlance;
    }
    public long getIdespecie() {
        return this.idespecie;
    }
    
    public void setIdespecie(long idespecie) {
        this.idespecie = idespecie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PescaId) ) return false;
		 PescaId castOther = ( PescaId ) other; 
         
		 return (this.getIdlance()==castOther.getIdlance())
 && (this.getIdespecie()==castOther.getIdespecie());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdlance();
         result = 37 * result + (int) this.getIdespecie();
         return result;
   }   


}


