package com.xeopesca.webapp.model.vos;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA

import org.hibernate.annotations.GenericGenerator;



/**
 * Pesca generated by hbm2java
 */
@Entity
@Table(name = "pesca")
public class Pesca  implements java.io.Serializable {

	 @Id
	 @GeneratedValue(generator = "increment")
	 @GenericGenerator(name = "increment", strategy = "increment")
     private Long id;
     private Long idlance;
     private Long idespecie;
     private Float peso;
     private Long ud;
     private Float pesodescarte;
     private Float uddescarte;
     
     @JoinColumn(name = "idlance",insertable=false, updatable=false)
     @ManyToOne(optional = false, fetch = FetchType.LAZY)
     private Lance lance;
     
     @JoinColumn(name = "idespecie",insertable=false, updatable=false)
     @ManyToOne(optional = false, fetch = FetchType.LAZY)
     private Especie especie;
  

    public Pesca() {
    }


    
   
  
   
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public Long getUd() {
        return this.ud;
    }
    
    public void setUd(Long ud) {
        this.ud = ud;
    }
    public Float getPesodescarte() {
        return this.pesodescarte;
    }
    
    public void setPesodescarte(Float pesodescarte) {
        this.pesodescarte = pesodescarte;
    }
    public Float getUddescarte() {
        return this.uddescarte;
    }
    
    public void setUddescarte(Float uddescarte) {
        this.uddescarte = uddescarte;
    }





	public Long getId() {
		return id;
	}





	public void setId(Long id) {
		this.id = id;
	}





	public Long getIdlance() {
		return idlance;
	}





	public void setIdlance(Long idlance) {
		this.idlance = idlance;
	}





	public Long getIdespecie() {
		return idespecie;
	}





	public void setIdespecie(Long idespecie) {
		this.idespecie = idespecie;
	}






	public Lance getLance() {
		return lance;
	}






	public void setLance(Lance lance) {
		this.lance = lance;
	}






	public Especie getEspecie() {
		return especie;
	}






	public void setEspecie(Especie especie) {
		this.especie = especie;
	}




}


