/* --------------------------------------------------------------------
 This file is part of xeoPesca

Copyright (C) 2013 - Pablo Belay Fernández 
This program is free software: you can redistribute it
and/or modify it under the terms of the GNU General
Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your
option) any later version.
This program is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License
for more details.
You should have received a copy of the GNU General Public
License along with this program. If not, see
http://www.gnu.org/licenses/gpl-3.0-standalone.html
--------------------------------------------------------------------*/
package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoloxiabarco generated by hbm2java
 */
public class Tipoloxiabarco  implements java.io.Serializable {


     private long tipo;
     private String descripcion;
     private Set barcos = new HashSet(0);

    public Tipoloxiabarco() {
    }

	
    public Tipoloxiabarco(long tipo, String descripcion) {
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Tipoloxiabarco(long tipo, String descripcion, Set barcos) {
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.barcos = barcos;
    }
   
    public long getTipo() {
        return this.tipo;
    }
    
    public void setTipo(long tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getBarcos() {
        return this.barcos;
    }
    
    public void setBarcos(Set barcos) {
        this.barcos = barcos;
    }




}


