package com.xeopesca.webapp.model.vos;
// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoloxiabarco generated by hbm2java
 */
public class Tipoloxiabarco  implements java.io.Serializable {


     private long tipo;
     private String descripcion;
     private Set barcos = new HashSet(0);

    public Tipoloxiabarco() {
    }

	
    public Tipoloxiabarco(long tipo, String descripcion) {
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Tipoloxiabarco(long tipo, String descripcion, Set barcos) {
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.barcos = barcos;
    }
   
    public long getTipo() {
        return this.tipo;
    }
    
    public void setTipo(long tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getBarcos() {
        return this.barcos;
    }
    
    public void setBarcos(Set barcos) {
        this.barcos = barcos;
    }




}


