/* --------------------------------------------------------------------
 This file is part of xeoPesca

Copyright (C) 2013 - Pablo Belay Fernández 
This program is free software: you can redistribute it
and/or modify it under the terms of the GNU General
Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your
option) any later version.
This program is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License
for more details.
You should have received a copy of the GNU General Public
License along with this program. If not, see
http://www.gnu.org/licenses/gpl-3.0-standalone.html
--------------------------------------------------------------------*/
package com.xeopesca.webapp.model.vos;

// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "increment")
	@GenericGenerator(name = "increment", strategy = "increment")
	private long id;
	
	// @ Type(type = "com.xeopesca.webapp.model.vos.Barco")
   //private Barco barco;
		 
	private String login;
		
	private String nome;
	
	private String apelidos;
	
	private String contrasinal;
	
	private String tipousuario;
	
	private Long patron_autoriza;
	
	private Long idbarco; 
	/*
	@Transient
	@OneToMany (fetch = FetchType.LAZY, targetEntity=Barco.class)
	@JoinColumn(name="id", referencedColumnName="idarmador")
	private List<Barco> barcosArmador;
	*/
	/* @Transient
	 @JoinColumn(name = "idbarco",insertable=false, updatable=false)
     @OneToOne(optional = false, fetch = FetchType.LAZY)
     private Barco barcoPatron;
*/

	public Usuario() {
	}

	public Usuario(long id, Barco barco, String login, String nome,
			String apelidos, String contrasinal, String tipousuario) {
		this.id = id;
		this.login = login;
		this.nome = nome;
		this.apelidos = apelidos;
		this.contrasinal = contrasinal;
		this.tipousuario = tipousuario;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

//	Para mostrar mensaxe de validación empregamos unha definición de mensaxe creada por defecto polo propio framework
//	que non é necesario indicar aquí, definimos a mensaxe para internacionalización no properties:
//	exemplo: NoBlank.usuario.login, Length.usuario.login, etc....
	
	@NotBlank
	@Length(min=4,max=10)  
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@NotBlank
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@NotBlank 
	public String getApelidos() {
		return this.apelidos;
	}

	public void setApelidos(String apelidos) {
		this.apelidos = apelidos;
	}

	@NotBlank
	@Length(min=5)
	public String getContrasinal() {
		return this.contrasinal;
	}

	public void setContrasinal(String contrasinal) {
		this.contrasinal = contrasinal;
	}

	@NotBlank 
	public String getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(String tipousuario) {
		this.tipousuario = tipousuario;
	}

	public Long getPatron_autoriza() {
		return patron_autoriza;
	}

	public void setPatron_autoriza(Long patron_autoriza) {
		this.patron_autoriza = patron_autoriza;
	}

	public Long getIdbarco() {
		return idbarco;
	}

	public void setIdbarco(Long idbarco) {
		this.idbarco = idbarco;
	}
/*
	public List<Barco> getBarcosArmador() {
		return barcosArmador;
	}

	public void setBarcosArmador(List<Barco> barcosArmador) {
		this.barcosArmador = barcosArmador;
	}
*/
	/*
	public Barco getBarcoPatron() {
		return barcoPatron;
	}

	public void setBarcoPatron(Barco barcoPatron) {
		this.barcoPatron = barcoPatron;
	}
	*/

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Usuario [id=");
		builder.append(id);
		builder.append(", login=");
		builder.append(login);
		builder.append(", nome=");
		builder.append(nome);
		builder.append(", apelidos=");
		builder.append(apelidos);
		builder.append(", contrasinal=");
		builder.append(contrasinal);
		builder.append(", tipousuario=");
		builder.append(tipousuario);
		builder.append(", patron_autoriza=");
		builder.append(patron_autoriza);
		builder.append(", idbarco=");
		builder.append(idbarco);
		builder.append("]");
		return builder.toString();
	}
}
