package com.xeopesca.webapp.model.vos;

// Generated 05-oct-2012 22:49:11 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	@Id
	@GeneratedValue(generator = "increment")
	@GenericGenerator(name = "increment", strategy = "increment")
	private long id;
	
	//@Type(type = "com.xeopesca.webapp.model.vos.Barco")
	private Barco barco;
	private String login;
	private String nome;
	private String apelidos;
	private String contrasinal;
	private String tipousuario;
	//private Set barcos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(long id, Barco barco, String login, String nome,
			String apelidos, String contrasinal, String tipousuario) {
		this.id = id;
		this.barco = barco;
		this.login = login;
		this.nome = nome;
		this.apelidos = apelidos;
		this.contrasinal = contrasinal;
		this.tipousuario = tipousuario;
	}

	public Usuario(long id, Barco barco, String login, String nome,
			String apelidos, String contrasinal, String tipousuario, Set barcos) {
		this.id = id;
		this.barco = barco;
		this.login = login;
		this.nome = nome;
		this.apelidos = apelidos;
		this.contrasinal = contrasinal;
		this.tipousuario = tipousuario;
	//	this.barcos = barcos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Barco getBarco() {
		return this.barco;
	}

	public void setBarco(Barco barco) {
		this.barco = barco;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getApelidos() {
		return this.apelidos;
	}

	public void setApelidos(String apelidos) {
		this.apelidos = apelidos;
	}

	public String getContrasinal() {
		return this.contrasinal;
	}

	public void setContrasinal(String contrasinal) {
		this.contrasinal = contrasinal;
	}

	public String getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(String tipousuario) {
		this.tipousuario = tipousuario;
	}
/*
	public Set getBarcos() {
		return this.barcos;
	}

	public void setBarcos(Set barcos) {
		this.barcos = barcos;
	}
*/
}
